on:
  push:
    branches:
      - 'main'

name: Release to public with tag next, after linting and testing

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Check, lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  release:
    name: Release to npmjs.com
    needs: [check, test]
    env:
      PROJECT_NAME_UNDERSCORE: svg_diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Build npm package
        run: npm run build
      - name: "Store npm token"
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_COM_API_TOKEN }}
      - name: 'Publish to npmjs.com'
        run: npm publish --tag next
