on: [push]
name: Test with Code Coverage

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
#      - name: Generate test result and coverage report
#        run: |
#          cargo install cargo2junit grcov;
#          cargo test $CARGO_OPTIONS -- -Z unstable-options --format json | cargo2junit > results.xml;
#          zip -0 ccov.zip `find . \( -name "$PROJECT_NAME_UNDERSCORE*.gc*" \) -print`;
#          grcov ccov.zip -s . -t lcov --llvm --ignore-not-existing --ignore "/*" --ignore "tests/*" -o lcov.info;
#      - name: Upload test results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        with:
#          check_name: Test Results
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: results.xml
##      - name: Upload to CodeCov
##        uses: codecov/codecov-action@v1
##        with:
##          # required for private repositories:
##          # token: ${{ secrets.CODECOV_TOKEN }}
##          files: ./lcov.info
##          fail_ci_if_error: true
